# Generated by Django 6.0.6 on 2026-06-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10, verbose_name='name')),
                ('email', models.EmailField(max_length=10, verbose_name='email')),
                ('mobile', models.CharField(max_length=10, verbose_name='mobile')),
                ('address', models.TextField(max_length=10, verbose_name='address')),
            ],
        ),
    ]
